name: crw-preferences

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash
    working-directory: packages/crw-preferences

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        env:
          CARGO_BIN_NAME: test
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

  lints:
    name: Lints (fmt + clippy)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt
        run: CARGO_BIN_NAME=test cargo fmt --all -- --check
      - name: Run cargo clippy
        run: CARGO_BIN_NAME=test cargo clippy -- -D warnings
      - name: Run cargo test
        run: CARGO_BIN_NAME=test cargo test --all-features
